//%attributes = {}
//%attributes = {}

var $projectFolder : 4D:C1709.Folder
var $importsFolder : 4D:C1709.Folder
var $file : 4D:C1709.File
var $records : Collection
var $record : Object
var $inventory : cs:C1710.InventoryEntity
var $result : Object
var $uniqueID : Text
var $stockNum : Text
var $travellerLot : Text
var $lot : cs:C1710.LotEntity
var $classificationDataClass : 4D.DataClass
var $classification : 4D.Entity
var $classificationValue : Text
var $unitsDataClass : 4D.DataClass
var $unit : 4D.Entity
var $unitValue : Text
var $created : Integer
var $updated : Integer

TRUNCATE TABLE:C1051([Inventory:126])

$projectFolder:=Folder:C1567(fk database folder:K87:14)
$importsFolder:=$projectFolder.folder("project/imports")
$file:=$importsFolder.file("inventory_export.json")

If (Not:C34($file.exists))
	ALERT:C41("Import file not found: "+$file.platformPath)
Else 
	$records:=JSON Parse:C1218($file.getText())
	$classificationDataClass:=ds["InventoryClassification"]
	$unitsDataClass:=ds["InventoryUnits"]
	
	$created:=0
	$updated:=0
	
	For each ($record; $records)
		$uniqueID:=String:C10($record.UniqueID)
		$stockNum:=String:C10($record.Stock_Num)
		$travellerLot:=String:C10($record.travellerLot)
		
		$inventory:=Null:C1517
		
		// Try by unique id first, then fallback to stock number.
		If ($uniqueID#"")
			$inventory:=ds:C1482.Inventory.query("UUID = :1"; $uniqueID).first()
		End if 
		
		If ($inventory=Null:C1517)
			If ($stockNum#"")
				$inventory:=ds:C1482.Inventory.query("stockNum = :1"; $stockNum).first()
			End if 
		End if 
		
		If ($inventory=Null:C1517)
			$inventory:=ds:C1482.Inventory.new()
			$created:=$created+1
		Else 
			$updated:=$updated+1
		End if 
		
		// Map exported legacy keys -> current Inventory table fields.
		$inventory.partNumber:=$record.Part_Number
		$inventory.vendor:=$record.Vendor
		$inventory.description:=$record.Description
		$inventory.qtyInStock:=$record.Qty_in_Stock
		$inventory.units:=$record.Units
		$inventory.unitCost:=$record.Unit_Cost
		$inventory.division:=$record.Division
		$inventory.stockNum:=$record.Stock_Num
		$inventory.dateIn:=$record.Date_in
		$inventory.expirationDate:=$record.Expiration_Date
		$inventory.receivedBy:=$record.Recd_by
		$inventory.location:=$record.Bin_Location
		$inventory.actualValue:=$record.Current_Actual_Value
		$inventory.initialQty:=$record.Original_Qty
		$inventory.partLotNumber:=$record.LotNumber
		$inventory.classification:=$record.Classification
		$inventory.currency:=$record.Currency
		$inventory.availableQty:=$record.AvailableQty
		$inventory.docsInServer:=$record.DocumentsinDocserver
		$inventory.customerSpecific:=$record.CustomerSpecific
		
		// Link to InventoryClassification table when available.
		$classificationValue:=String:C10($record.Classification)
		If ($classificationDataClass#Null:C1517) && ($classificationValue#"")
			$classification:=$classificationDataClass.query("code = :1"; $classificationValue).first()
			If ($classification=Null:C1517)
				$classification:=$classificationDataClass.query("name = :1"; $classificationValue).first()
			End if 
			If ($classification#Null:C1517)
				$inventory["UUID_InventoryClassification"]:=$classification.UUID
			End if 
		End if 
		
		// Link to InventoryUnits table when available.
		$unitValue:=String:C10($record.Units)
		If ($unitsDataClass#Null:C1517) && ($unitValue#"")
			$unit:=$unitsDataClass.query("name = :1"; $unitValue).first()
			If ($unit#Null:C1517)
				$inventory["UUID_InventoryUnits"]:=$unit.UUID
			End if 
		End if 
		
		// Preserve source UUID when provided; otherwise keep existing/new autogenerated UUID.
		If ($uniqueID#"")
			$inventory.UUID:=$uniqueID
		End if 
		
		// Link inventory to lot using traveller lot number from import json.
		If ($travellerLot#"")
			$lot:=ds:C1482.Lot.query("lotNumber = :1"; $travellerLot).first()
			If ($lot#Null:C1517)
				$inventory.UUID_Lot:=$lot.UUID
				$inventory.UUID_Job:=$lot.UUID_Job
			End if 
		End if 
		
		$result:=$inventory.save()
		If (Not:C34($result.success))
			TRACE:C157
		End if 
	End for each 
	
	ALERT:C41("Import termine - created: "+String:C10($created)+" | updated: "+String:C10($updated))
End if 
