//%attributes = {}


// Method: _util_generate_entry_structure

// Parameter: $tableName (Text)
#DECLARE($tableName : Text)

var $sources : 4D:C1709.Folder
var $classFile : 4D:C1709.File
var $code : Text
var $moduleName : Text:="MainModule"

$sources:=Folder:C1567(fk project folder).folder("Sources")

// --- 1. GENERATE DATACLASS (.4dm) ---
$classFile:=$sources.folder("Classes").file($tableName+".4dm")

$code:="// Class generated by Crawler\n"
$code+="Class extends DataClass\n\n"
$code+="local Function entryDefinition()->$entry : cs.sfw_definitionEntry\n"
$code+="\t$entry:=cs.sfw_definitionEntry.new(\""+$tableName+"\"; [\""+$moduleName+"\"]; \"ICON\")\n"
$code+="\t$entry.setDataclass(\""+$tableName+"\")\n"
$code+="\t$entry.setPanel(\"panel_"+Lowercase:C14($tableName)+"\")\n"

// You can loop through the datastore to guess columns
var $fields : Collection
$fields:=ds:C1482[$tableName].getInfo().attributes.query("kind = 'storage'")

For each ($field; $fields)
	If ($field.type="text")
		$code+="\t$entry.setLBItemsColumn(\""+$field.name+"\"; \""+$field.name+"\"; \"width:150\")\n"
	End if 
End for each 

$code+="\treturn $entry"

$classFile.setText($code)

// --- 2. GENERATE FORM (form.json) ---
// You would create the folder /Forms/panel_tablename/
// and use File.setText(JSON Stringify($formObject))
// based on a template JSON.
